ports:
  - port: 5173
    onOpen: open-preview

tasks:
  - name: Install Dependencies and Start Dev Server
    init: npm install
    command: npm run dev

vscode:
  extensions:
    - svelte.svelte-vscode
